// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqC6VJ4eQessvCePHFiyHQG4NIEigEjNI',
    appId: '1:359662441201:web:7476f1038b3b0e19c24f50',
    messagingSenderId: '359662441201',
    projectId: 'abi-s-recipes',
    authDomain: 'abi-s-recipes.firebaseapp.com',
    storageBucket: 'abi-s-recipes.appspot.com',
    measurementId: 'G-1RHMVHRZ3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHm3g8Uz0YP9tZrMX67Fo4DBp7e7w3uIQ',
    appId: '1:359662441201:android:df6abd6437a09505c24f50',
    messagingSenderId: '359662441201',
    projectId: 'abi-s-recipes',
    storageBucket: 'abi-s-recipes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-M_aWxX1fM1iTS_5qhi3992b9RyEbI4s',
    appId: '1:359662441201:ios:be2fdf54a436839cc24f50',
    messagingSenderId: '359662441201',
    projectId: 'abi-s-recipes',
    storageBucket: 'abi-s-recipes.appspot.com',
    iosClientId: '359662441201-cokn19d75ipteun6q25ll3vt08tdpe5g.apps.googleusercontent.com',
    iosBundleId: 'com.mullr.abisRecipes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-M_aWxX1fM1iTS_5qhi3992b9RyEbI4s',
    appId: '1:359662441201:ios:be2fdf54a436839cc24f50',
    messagingSenderId: '359662441201',
    projectId: 'abi-s-recipes',
    storageBucket: 'abi-s-recipes.appspot.com',
    iosClientId: '359662441201-cokn19d75ipteun6q25ll3vt08tdpe5g.apps.googleusercontent.com',
    iosBundleId: 'com.mullr.abisRecipes',
  );
}
